mod auto_launch;
mod clipboard;
mod front_logger;
mod hide_notification;
mod is_debug;
mod local_storage;
mod monitor_info;
mod preview_page;
mod quit;
mod request_client;
mod request_refer_image;
mod resource_location;
mod should_silence;
mod system_notification;
mod update_available;
mod setting_page;

pub use self::auto_launch::{auto_launch_setting, set_auto_launch};
pub use clipboard::copy_image;
pub use front_logger::front_logger;
pub use hide_notification::hide_notification;
pub use is_debug::is_debug;
pub use local_storage::{get_item, set_item};
pub use monitor_info::{get_monitor_info, message_beep};
pub use preview_page::{back_preview, read_detail};
pub use quit::quit;
pub use request_client::send_request;
pub use request_refer_image::request_refer_image;
pub use resource_location::{get_app_cache_path, get_app_config_path};
pub use should_silence::should_silence;
pub use system_notification::send_system_notification;
pub use setting_page::{close_setting_page, open_setting_page};
