name: Build/release

on:
  push:
    branches:
      - release

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const tags = (await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })).data.map((tag) => tag.name);
            const tagName = `app-v${process.env.PACKAGE_VERSION}`;

            console.log(`${tags} check is contain ${tagName}`);

            if (tags.includes(tagName)){
              core.setFailed(`tag name '${tagName}' Exist`);
              return null;
            }
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: `CeobeCanteenDesktop v${process.env.PACKAGE_VERSION}`,
              draft: true,
              prerelease: false
            })
            return data.id

  release:
    runs-on: ${{ matrix.os }}
    needs:
      - create-release

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install py2.7 for macos
        uses: actions/setup-python@v4
        if: ${{ matrix.os == 'macos-latest' }}
        id: setup-py
        with:
          python-version: 'pypy2.7'

      - name: install dependence
        run: npm install
      - name: install dmg-license
        if: ${{ matrix.os == 'macos-latest' }}
        run: npm i dmg-license

      - name: build app for macos
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          PYTHON_PATH: ${{ steps.setup-py.outputs.python-path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:build

      - name: build app
        if: ${{ matrix.os != 'macos-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run electron:build

      - name: pack release file to /release
        run: |
          npm add archiver
          npm run pack:release
      
      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
  
      - name: upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_dir="./release/"
          ls $release_dir | while read file; do
            gh release upload --clobber app-v${{ env.PACKAGE_VERSION }} "$release_dir$file"
          done

      # upload build test reports
      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: electron-build-reports-${{ runner.os }}
          path: /home/runner/.npm/_logs/

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    needs: [create-release, release]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })

  remove-failure-release:
    runs-on: ubuntu-20.04
    needs:
      - release
      - create-release
    if: ${{ failure() }}

    steps:
      - name: publish release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            const releaseId = process.env.release_id;
            if ( releaseId ){
            github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
            })
            }
